### ISSUE TITLE
无法开启本地调试模式

### ISSUE THREAD

**Issue by hequndev** [Risyen/Mia.bio#10]
在项目中使用npm i安装完依赖之后使用npm run dev开启本地调试模式报错
Module not found: Can't resolve 'react/jsx-dev-runtime'

**Comment by XeryYue** [comment]
@hequndev 可以使用yarn安装试一下

**Comment by hequndev** [comment]
重新删除依赖后 使用 yarn 重新安装了依赖，依旧出现该问题。

**Comment by XeryYue** [comment]
@hequndev  我在拉取代码后发现确实会这样。我会在修复以后通知你。

**Comment by hequndev** [comment]
> @hequndev 我在拉取代码后发现确实会这样。我会在修复以后通知你。

好的。谢谢

**Comment by XeryYue** [comment]
@hequndev  我已解决这个问题。升级了package.json相关的依赖。 拉取最新代码即可。

**Comment by XeryYue** [comment]
@hequndev  我刚刚自己合并了代码发现升级到17确实比较麻烦 最近没什么时间我把next版本降到9.5.5 ，react降到16.不好意思了。
